### ISSUE TITLE
ALBERT Training Time

### ISSUE THREAD

**Issue by kkaehler** [to-aoki/my-pytorch-bert#1]
Hi - I saw that you'd implemented the parameter sharing and embedding factorization for Albert. Was curious how that had worked out? How long did it take to run the pre-training? As far as I'm aware, you have to train ALBERT from scratch, right? There aren't any weights available yet to fine tune on.

**Comment by to-aoki** [comment]
Thanks for your questions. Pre-learning is not yet complete because my computer resources are poor.
I don't know if it will be a guide, but ALBERT-BASE is a Google-Colab GPU type and is about 4 batches / second.

**Comment by to-aoki** [comment]
Although it was late, I uploaded a Japanese model. Please use it if you like.
